spring.datasource.url=jdbc:postgresql://localhost:5432/jobscheduler
spring.datasource.username=postgres
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# AWS Config
aws.region=us-east-1
aws.sqs.queue-url=https://sqs.us-east-1.amazonaws.com/585707316380/job-scheduler-queue
aws.access-key=YOUR_ACCESS_KEY_HERE
aws.secret-key=YOUR_SECRET_KEY_HERE